# site.yml
#
# ansible-playbook -i vagrant-inventory provision/site.yml 

 - hosts: powerdns

  roles:
          - { role: PowerDNS.pdns, become: true }
  vars:
    database_name: '/var/lib/powerdns/db.sqlite'
    pdns_config:
      master: true
      slave: false
      local-address: '192.168.44.10'
    pdns_backends:
      gsqlite3:
        database: "{{ database_name }}"
        dnssec: yes
    pdns_sqlite_databases_locations:
      - "{{ database_name }}"

