---

# site.yml
#
# ansible-playbook -i vagrant-inventory provision/site.yml 

# ----------------------------------------------------------------
- hosts: powerdns

  vars_files: 
    - variables.yaml

  roles:
    - { role: PowerDNS.pdns, become: true }

  tasks:
    - name: verifica si el dominio example.com esta creado
      shell: |
        pdnsutil list-zone example.com

      become: true
      ignore_errors: true
      changed_when: false
      register: reg_example_com


    - name: crea un dominio example.com y agrega algunas entradas
      shell: |
        pdnsutil create-zone example.com ns1.example.com
        pdnsutil add-record example.com '' MX '25 mail.example.com'
        pdnsutil add-record example.com. www A 192.168.88.1

      become: true
      when: reg_example_com.rc != 0

# ----------------------------------------------------------------
- hosts: nsedit

  vars_files: 
    - variables.yaml

  roles:
    - { role: nsedit, become: true }

